name: note_app
description: A new Flutter project.

publish_to: 'none'


version: 1.5.1+3

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  time_pickerr: ^1.0.6
  toastification: 1.0.2
  persian_datetime_picker: ^2.6.0
  flutter_animate: ^4.2.0+1
  adaptive_theme: ^3.4.1
  url_launcher: ^6.2.1
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter



  hive_generator: ^2.0.1

  build_runner: ^2.4.6


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/

 
  fonts:
    - family: shabnam
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 400








